src/Entity/User.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nomUser = null;

    #[ORM\Column(length: 50)]
    private ?string $prenomUser = null;

    #[ORM\Column(length: 100, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\OneToMany(mappedBy: 'idUser', targetEntity: Avis::class)]
    private Collection $avis;

    #[ORM\OneToMany(mappedBy: 'idUser', targetEntity: Restaurant::class)]
    private Collection $restaurants;


    public function __construct()
    {
        $this->avis = new ArrayCollection();
        $this->restaurants = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nomUser;
    }

    public function setNom(string $nomUser): static
    {
        $this->nomUser = $nomUser;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenomUser;
    }

    public function setPrenom(string $prenomUser): static
    {
        $this->prenomUser = $prenomUser;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreateAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setUser($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getUser() === $this) {
                $avi->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Restaurant>
     */
    public function getRestaurants(): Collection
    {
        return $this->restaurants;
    }

    public function addRestaurant(Restaurant $restaurant): static
    {
        if (!$this->restaurants->contains($restaurant)) {
            $this->restaurants->add($restaurant);
            $restaurant->setIdUser($this);
        }

        return $this;
    }

    public function removeRestaurant(Restaurant $restaurant): static
    {
        if ($this->restaurants->removeElement($restaurant)) {
            // set the owning side to null (unless already changed)
            if ($restaurant->getIdUser() === $this) {
                $restaurant->setIdUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;

#[Route('admin/users', name: 'user_')]
class UserController extends AbstractController
{
    #[Route('/', name: 'liste')]
    public function index(UserRepository $userRepo, PaginatorInterface $paginator, Request $request): Response
    {
        $data = $userRepo->findBy([], ['nomUser' => 'ASC']);

        $users = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('admin/users.html.twig', [
            'users' => $users
        ]);
    }

    #[Route('/delete/{id}', name: 'delete')]
    public function remove(User $user, EntityManagerInterface $em): Response
    {
        if(!$user) {
            throw $this->createNotFoundException('Utilisateur non trouvé');
        }

        $avis = $user->getAvis();

        foreach($avis as $avs) {
            
            $em->remove($avs);
        }

        $em->remove($user);

        $em->flush();

        return $this->redirectToRoute('user_liste');
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\UserFormType;
use App\Repository\RestaurantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

#[Route('/profil', name: 'app_profil_')]
class UserController extends AbstractController
{
    

    public function __construct(private AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    #[Route('/', name: 'info')]
    public function profil(RestaurantRepository $restoRepo): Response
    {
        if ($this->authorizationChecker->isGranted('ROLE_RESTAURATEUR')) {
            // Récupérer l'utilisateur connecté
            $user = $this->getUser();

            // Récupérer les restaurants liés à cet utilisateur
            $restaurants = $restoRepo->findBy(['idUser' => $user]);

            return $this->render('user/profilResto.html.twig', [
                'restaurants' => $restaurants,
            ]);
        }

        return $this->render('user/profil.html.twig');
    }
    

    #[Route('/setProfil', name: 'set')]
    public function setUser(Request $request, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(UserFormType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('app_profil_info');
        }

        return $this->render('user/setProfil.html.twig', [
            'form' => $form->createView(),
        ]);
    }


}

templates/user/avis.html.twig
{% extends "base.html.twig" %}

{% block title %}Gestion d'avis{% endblock %}

{% block body %}

    {% include "_Partials/_header.html.twig" %}

    <div class=" h-screen flex mb-6 relative">

        {% include "_Partials/_menuRestaurateur.html.twig" %}

        <div class="pt-6 px-4 w-full md:px-10 lg:px-20 ">

            <button class="p-2 mb-4 border border-black rounded text-white bg-black md:static" id="menutoggle">Plus</button>

            <h1 class="text-center text-xl font-bold mb-10 py-1 bg-black text-white rounded-l rounded-r">les Avis</h1>

            {% if allAvis %}
                <div class="h-2/3">
                    <table class="w-full border-collapse border">
                        <thead>
                            <tr class="bg-black text-white">
                                <th class="p-2">Restaurant</th>
                                <th class="p-2">Commentaire</th>
                                <th class="p-2">Note</th>
                            </tr>
                        </thead>
                        <tbody>
                           {% for avisData in allAvis %}
                                {% for avis in avisData.avis %}
                                    <tr class="border-b">
                                        <td class="p-2 border-r ">{{ avisData.restaurant.nomResto }}</td>
                                        <td class="p-2 border-r ">{{ avis.commentaire }}</td>
                                        <td class="p-2 border-r ">{{ avis.note }}</td>
                                    </tr>
                                {% endfor %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="h-3/4 flex justify-center items-center mb-6">
                    <div class="">
                        <h2 class="text-xl text-green-500 text-center font-bold">Vous n'avez pas encore d'avis</h2>
                    </div>
                </div>
            {% endif %}


        </div>
    </div>


    {% include "_Partials/_footer.html.twig" %}

{% endblock %}

templates/user/details.html.twig
{% extends "base.html.twig" %}

{% block title %}Details sur le restaurant{% endblock %}

{% block body %}

    {% include "_Partials/_header.html.twig" %}

    <div class="px-10 pt-10">
        
        <h1 class="text-xl text-center font-bold mb-8">Mettez à jour les infos de votre restaurant</h1>

        {{ form_start(restoForm, {'attr': {'class': 'flex '}})}}

            <div class="flex flex-col w-full">
            
                <div class="flex flex-col mb-2 ">
                    {{form_row(restoForm.nomResto, {'attr': {'class': 'block outline-none border-b p-2 my-4 w-full', 'placeholder': 'Nom'}})}}
                </div>
                <div class="flex flex-col mb-2 ">
                    {{form_row(restoForm.description, {'attr': {'class': 'block outline-none border-b p-2 my-4 w-full resize-none', 'placeholder': 'En quelque mots ce que vous vendez'}})}}
                </div>
                <div class="flex flex-col mb-2 ">
                    {{form_row(restoForm.adresse, {'attr': {'class': 'block outline-none border-b p-2 my-4 w-full', 'placeholder': '8 rue du jardin'}})}}
                </div>
                <div class="flex flex-col mb-2 ">
                    {{form_row(restoForm.codePostale, {'attr': {'class': 'block outline-none border-b p-2 my-4 w-full', 'placeholder': 'code Postale'}})}}
                </div>
                <div class="flex flex-col mb-2 ">
                    {{form_row(restoForm.ville, {'attr': {'class': ' block outline-none border-b p-2 my-4 w-full', 'placeholder': 'ville'}})}}
                </div>
                <div class="flex flex-col mb-2 ">
                    {{form_row(restoForm.telephone, {'attr': {'class': 'block outline-none border-b p-2 my-4 w-full', 'placeholder': 'téléphone',}})}}
                </div>
                <div>
                    <h2 class="text-xl font-semibold">Galerie d'images</h2>
                    <div class="">
                        {% if restoForm.images %}
                            {% for image in restoForm.images %}
                                <img src="{{ asset('assets/uploads/restaurants/mini/250x250-' ~ image.nomImage)}}" alt="Image" class="m-4" width = "150"/>
                            {% endfor %}

                        {% else %}
                            <h2>Aucune images touvées</h2>
                        {% endif %}
                    </div>
                    <div>
                        {{form_row(restoForm.images, {'attr': {'class': 'p-2 my-4 w-full'}})}}
                    </div>
                </div>

                <input type="submit" class="bg-black text-white rounded py-2 my-4 w-full" value="{{ button_label|default('Ajouter') }}"/>

            </div>
            
            
        {{ form_end(restoForm)}}
    
    </div>


    {% include "_Partials/_footer.html.twig" %}

{% endblock %}

templates/user/newResto.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajouter un restaurant{% endblock %}

{% block body %}

    <div class="p-10">
    
        <div class="mb-6">
            <a href="{{ path('accueil')}}" class="text-2xl font-bold text-green-500">RestoRate</a>
        </div>

        <h1 class="text-center text-2xl font-bold">Ajouter un restaurant</h1>

        <div class="md:flex flex-col items-center justify-center md:px-20">
            {% include "_Partials/_formResto.html.twig" %}
        </div>
    
    </div>

{% endblock %}

templates/user/profil.html.twig
{% extends "base.html.twig" %}

{% block title %}Profil Utilsateur{% endblock %}

{% block body %}

    {% include "_Partials/_header.html.twig" %}


    <div class="flex flex-col w-full justify-center h-screen p-10">
    
        <h1 class="text-2xl"><span class="mr-2 text-2xl font-bold">Hello</span> {{app.user.nom}} {{app.user.prenom}} !</h1>

        <div class="p-4 mt-4 ">
            <h2 class="text-2xl bg-gray-300 text-center">Vos informations personnelles</h2>
            <div class="mt-6 p-4 border">
                <p class="mb-2"><span class="mr-4">Nom:</span>{{app.user.nom}}</p>
                <p><span class="mr-4">Prenom:</span>{{app.user.prenom}}</p>
            </div>
        </div>
        
        <div class="mt-8 p-4">
            <h2 class="text-2xl pl-4 bg-gray-300">Actions</h2>
        </div>

        <ul class="p-4">
            <li><a href="{{ path('app_profil_set')}}">Modifier mes informations</a></li>
            <li class="mt-2">supprimer mon compte</li>
        </ul>
    
    </div>    
        


    {% include "_Partials/_footer.html.twig" %}

{% endblock %}

templates/user/profilResto.html.twig
{% extends "base.html.twig" %}

{% block title %}Profil Utilsateur{% endblock %}

{% block body %}

    {% include "_Partials/_header.html.twig" %}


        <div class=" h-screen flex mb-6 relative">
        
            {% include "_Partials/_menuRestaurateur.html.twig" %}

            <div class="pt-6 px-4 w-full md:px-10 lg:px-20 ">

                <button class="p-2 mb-4 border border-black rounded text-white bg-black md:static" id="menutoggle">Plus</button>

                <h1 class="text-center text-xl font-bold mb-10 py-1 bg-green-500 text-white rounded-l rounded-r">Gerer mes restaurants</h1>

                {% if restaurants %}

                    <div class="h-2/3 ">
                        {% for resto in restaurants %}
                        
                            <div class="">
                                <div class="">
                                    <div class="flex justify-between w-full border p-2 bg-green-500 text-white mb-2 rounded-l rounded-r">
                                        <a href="{{ path('app_details', {'idResto': resto.id})}}" class="">{{ resto.nomResto }}</a>
                                        <a href="{{ path('app_delete', {'idResto': resto.id}) }}" class=" hover:underline">Supprimer</a>
                                    </div>
                                </div>

                            </div>

                        {% endfor %}
                    </div>    
                    
                    <div class="flex justify-end pr-6">
                        <a class="bg-green-500 text-white rounded-l rounded-r p-2" href="{{ path('new_resto')}}">Ajouter</a>
                    </div>
                    
                {% else %}

                    <div class="h-2/3 flex justify-center items-center mb-6">

                        <div class="">
                            <h2 class="text-xl text-green-500 text-center font-bold">Vous n'avez pas encore de restaurant </h2>
                        </div>

                    </div>

                    <div class="flex justify-end pr-6">
                        <a class="bg-green-500 text-white p-2 rounded-l rounded-r" href="{{ path('new_resto')}}">Commencer</a>
                    </div>

                {% endif %}

            </div>
        
        </div>    

    {% include "_Partials/_footer.html.twig" %}

{% endblock %}

templates/user/setProfil.html.twig
{% extends "base.html.twig" %}

{% block title %}{% endblock %}

{% block body %}

    {% include "_Partials/_header.html.twig" %}

    <div class="p-10 h-screen md:flex flex-col items-center">

        <h1 class="text-2xl text-center font-semibold mb-8">Modifier vos informations personnelles</h1>

        {{ form_start(form, {'attr': {'class': 'md:w-full md:p-20'}}) }}

            {{ form_row(form.prenom, {'attr': {'class': 'outline-none border-b  w-full mb-10 pt-4'}}) }}
            {{ form_row(form.password, {'attr': {'class': 'outline-none border-b  w-full mb-10 pt-4'}}) }}

            <input type="submit" value="modifier" class="w-full bg-black rounded text-white text-center py-1"/>
        {{ form_end(form) }}

    </div>

    {% include "_Partials/_footer.html.twig" %}


{% endblock %}